repository/answer.go, repository/camp.go, repository/event.go, repository/gorm/answer.go, repository/gorm/camp.go, repository/gorm/event.go, repository/gorm/option.go, repository/gorm/question.go, repository/gorm/question_group.go, repository/gorm/repository.go, repository/gorm/room.go, repository/gorm/user.go, repository/option.go, repository/question.go, repository/question_group.go, repository/repository.go, repository/room.go, repository/user.go, router/answers.go, router/camps.go, router/handler.go
Closes #14
実装そのものはあまり変更していないが、仕様変更に伴って明らかに不要になったメソッドなどは消した
また、書き換えを優先しているのでエラーが出るようになったところはとりあえずコメントアウトした
=> Repositoryのinterfaceと実装を分離

.gitignore, openapi.yaml, repository/event.go, repository/gorm/event.go, router/api.gen.go, router/events.go
今までは`DurationEvent`に相当するものしかなかったが、`Event = DurationEvent | MomentEvent | OfficialEvent`になったので必要な修正をする
=> 新しい`Event`のスキーマに対応

.github/workflows/main.yaml, .golangci.yaml, main.go, router/answers.go, router/camps_test.go, router/events.go, router/messages.go, router/options.go, router/question_groups.go, router/stubs.go, router/traq_event.go
Closes #32
デフォルトで有効になっているもの+未使用の引数のチェック
それ以外は今後必要に応じて追加していく
=> golangci-lintの設定を追加

converter/answer.go, converter/convert.go, repository/answer.go, repository/gorm/answer.go, repository/gorm/answer_test.go, repository/gorm/repository_test.go, repository/gorm/user_test.go, repository/mock/answer.go, router/answers.go, router/answers_test.go, router/camps_test.go, router/question_groups_test.go, testutil/random/random.go
=> `PostAnswers`を実装

main.go
=> 開発環境でのみCORSミドルウェアを有効化する

router/answers.go, router/answers_test.go
Introduce the PutAnswer method for editing survey responses and include comprehensive test cases to ensure its functionality across various answer types.
=> `PutAnswer`の実装

repository/gorm/answer.go, repository/gorm/answer_test.go, router/answers.go, router/answers_test.go
=> `UpdateAnswer`で更新後の`Answer`を取得する

repository/gorm/repository_test.go
Closes #67
これで本質的な修正になっているのか分からないが、とりあえず手元ではうまくいった
=> `unexpected EOF`が表示されないようにする

main.go
=> 環境変数からCORSの許可リストを取得

main.go, model/model.go, repository/camp.go, repository/gorm/camp.go, repository/gorm/camp_test.go, repository/mock/camp.go, router/dashboard.go, router/dashboard_test.go
=> 参加登録していないユーザーにはGetDashboardで404を返す

repository/gorm/payment.go, repository/gorm/payment_test.go, repository/gorm/repository_test.go, repository/mock/payment.go, repository/payment.go, router/payments.go, router/payments_test.go, router/stubs.go
=> Paymentの取得、更新を実装

repository/gorm/camp.go, repository/gorm/camp_test.go, router/camps.go, router/camps_test.go
=> 参加登録時にCampが存在しない／登録期間外の場合のエラーハンドリングを改善

api/api.gen.go, model/question.go, openapi.yaml, repository/gorm/question_group_test.go, repository/gorm/question_test.go, router/question_groups_test.go, router/questions_test.go
=> 質問を回答必須にするオプションを追加

api/api.gen.go, openapi.yaml, repository/answer.go, repository/gorm/answer.go, repository/gorm/answer_test.go, repository/gorm/payment_test.go, repository/gorm/question_group.go, repository/gorm/question_group_test.go, repository/gorm/repository_test.go, repository/mock/answer.go, repository/mock/question_group.go, repository/question_group.go, router/answers.go, router/answers_test.go, router/question_groups.go, router/question_groups_test.go
=> 管理者が質問グループごとの回答を取得できるように

migration/migrate.go, migration/v1.go, model/question.go
=> 質問テーブルにis_requiredカラムを追加するマイグレーションを実装

api/api.gen.go, openapi.yaml, repository/answer.go, repository/gorm/answer.go, repository/gorm/answer_test.go, repository/mock/answer.go, router/answers.go, router/answers_test.go
=> 管理者向けの回答追加機能を実装

router/questions.go, router/questions_test.go
=> 質問の更新時にtypeの変更を禁止する

.golangci.yaml, compose.yaml, main.go, openapi.yaml, repository/gormrepository/answer.go, router/answers.go, router/answers_test.go, router/camps.go, router/dashboard.go, router/events.go, router/messages.go, router/payments.go, router/question_groups.go, router/questions.go, router/rooms.go, router/router_test.go, router/users.go, testutil/random/random.go
=> 管理者がユーザーの回答を編集したらDMで通知する

.github/dependabot.yaml, README.md, compose.yaml, dev/caddy/Caddyfile
=> ローカルでクライアントを使えるようにする

api/api.gen.go, openapi.yaml, repository/camp.go, repository/gormrepository/camp.go, repository/gormrepository/camp_test.go, router/camps.go, router/camps_test.go, service/mockservice/traq.go, service/traq.go, service/traq_impl.go, service/traq_test.go
=> 管理者による参加登録の追加・削除を実装

openapi.yaml, repository/camp.go, repository/gormrepository/camp.go, repository/gormrepository/camp_test.go, repository/gormrepository/repository_test.go, repository/mockrepository/camp.go, router/camps.go, router/camps_test.go
=> 参加登録締め切り後の登録解除を禁止

openapi.yaml, repository/gormrepository/room_group.go, repository/gormrepository/room_group_test.go, repository/mockrepository/room_group.go, repository/room_group.go, router/room_groups.go, router/room_groups_test.go, router/stubs.go
=> RoomGroup取得処理の実装

repository/gormrepository/room_group.go, repository/gormrepository/room_group_test.go, repository/mockrepository/room_group.go, repository/room_group.go, router/room_groups.go, router/room_groups_test.go, router/stubs.go
=> RoomGroupの削除機能を実装

converter/convert.go, converter/room.go, openapi.yaml, repository/gormrepository/repository_test.go, repository/gormrepository/room.go, repository/gormrepository/room_group_test.go, repository/gormrepository/room_test.go, repository/mockrepository/room.go, repository/room.go, repository/user.go, router/rooms.go, router/rooms_test.go
=> 部屋の作成時に存在しないユーザーを追加できる問題を修正

repository/gormrepository/payment.go, repository/gormrepository/payment_test.go, repository/gormrepository/room.go, repository/gormrepository/room_test.go, repository/mockrepository/payment.go, repository/mockrepository/room.go, repository/payment.go, repository/room.go, router/dashboard.go, router/dashboard_test.go
=> DashboardにPaymentとRoomを含める

repository/gormrepository/payment.go, repository/gormrepository/payment_test.go, router/payments.go, router/payments_test.go
=> Paymentの金額を0に更新できるよう修正

openapi.yaml
=> 画像更新APIの定義を削除
